### PR TITLE
Use new coverage API

### PR DESCRIPTION
**Pull request by Tony-Proum**

### CODE REVIEW

**Comment by Tony-Proum** [comment]
We've merged https://github.com/sfeir-open-source/sonar-clover/pull/15 in this branch in order to benefits off all continuous integration chain before merging this Pull Request

**Comment by Tony-Proum** [comment]
After further test, it seems like this PR drop the support of previous version (LTS is not supported)
We have to work a bit to be able to provide a support for LTS version too in order to be able to release a new version

**Comment by mlschechter** [comment]
@Tony-Proum,

Is there anything anyone can do to help move this along?

**Comment by Tony-Proum** [comment]
Done, now, I have to configure deployment in the public artifact repository

**Comment by mlschechter** [comment]
@Tony-Proum,

I see that this was merged to `master`, and that's great. Can you please help me understand why I am having issues finding my commits on `master`? I only see them on this branch and the one I initially created.

Thanks!

**Comment by mlschechter** [comment]
@Tony-Proum,

Can you please provide a response to the above question?

Thanks!

**Pull request merged**
